Upgrade to angular 14
gazebo-web/gazebosim-app pull request #8
Opened 2022-08-20 18:04 UTC by nkoenig

This PR upgrades to angular 14. 

Along the way I had to ditch ngx-gallery, and replace it with swiper: 0d934253a0048a564ba9d1c9c3e05716f25d007c

2022-08-25 13:08 UTC, german-e-mas commented on angular.json
> +    "gazebosim": {
How did you make these changes on `angular.json`? I suggest creating a new project and checking the new `angular.json` file created for guidance.

2022-08-25 13:10 UTC, german-e-mas commented on angular.json
> +      "prefix": "app",
Any reason why not to use `gz` as a prefix?

2022-08-25 13:15 UTC, german-e-mas commented on angular.json
> +            "outputPath": "dist",
Since `app` changed to `gazebosim`, this could be `dist/gazebosim`. That was standard in Angular apps. If we change this, please double check that the github actions pipeline uses `dist` instead of `dist/:appName`.

2022-08-25 13:36 UTC, german-e-mas requested changes
Made a pass. I didn't made comments on the Slider dependency yet.

2022-08-25 13:36 UTC, german-e-mas commented on angular.json
> +              "src/sitemap.xml"
We do not have these files.

2022-08-25 13:36 UTC, german-e-mas commented on angular.json
> +              "node_modules/font-awesome/css/font-awesome.css"
Why do we need `font-awesome`?

2022-08-25 13:36 UTC, german-e-mas commented on angular.json
> +              "budgets": [
These are the default budgets. They could be misleading for this app.

2022-08-25 13:36 UTC, german-e-mas commented on angular.json
> +              "node_modules/marked/marked.min.js"
Why do we need `marked`?

2022-08-25 13:36 UTC, german-e-mas commented on angular.json
> +          "builder": "@angular-devkit/build-angular:karma",
I believe we used the custom webpack because of environment variables.

2022-08-25 13:36 UTC, german-e-mas commented on package.json
> +    "font-awesome": "^4.7.0",
Is this required by `swiper`?

2022-08-25 13:36 UTC, german-e-mas commented on src/app/admin/cloudsim/rules/simulation-rules.component.ts
> +    rule.value = Number(this.valueInputForm.value);
+1. Angular 14 introduced [typed forms](https://angular.io/guide/typed-forms). So these kind of fixes may arise during the conversion.

I'm not saying we should revisit all our forms, but it may be nice to do so as we work on a component that has one, in the future.

2022-08-25 13:36 UTC, german-e-mas commented on src/app/app-routing.module.ts
> +export class AppRoutingModule { }
+1 to have a routing module.

2022-08-25 13:36 UTC, german-e-mas commented on src/app/app.module.ts
> +    AppComponent,
These should be sorted alphabetically.

2022-08-25 13:36 UTC, german-e-mas commented on src/app/app.module.ts
> +    AdminElasticsearchService,
Same as before. These should be sorted alphabetically.

2022-08-25 13:36 UTC, german-e-mas commented on src/app/app.module.ts
> -  entryComponents: [
Are `entryComponents` no longer required?

2022-08-25 13:36 UTC, german-e-mas commented on src/app/collection/collection.service.ts
> +import { parseLinkHeader } from '@web3-storage/parse-link-header'
```suggestion
import { parseLinkHeader } from '@web3-storage/parse-link-header';
```

2022-08-25 13:36 UTC, german-e-mas commented on src/app/fuel-resource/fuel-resource.service.ts
> +import { parseLinkHeader } from '@web3-storage/parse-link-header'
```suggestion
import { parseLinkHeader } from '@web3-storage/parse-link-header';
```

2022-08-25 13:36 UTC, german-e-mas commented on src/app/portal/portal.service.ts
> +import { parseLinkHeader } from '@web3-storage/parse-link-header'
```suggestion
import { parseLinkHeader } from '@web3-storage/parse-link-header';
```

2022-08-25 14:57 UTC, german-e-mas commented
The infinite scrolling library should be updated, but I saw this [issue](https://github.com/orizens/ngx-infinite-scroll/issues/352#issue-614626964) (and [potential fix](https://github.com/orizens/ngx-infinite-scroll/issues/352#issuecomment-742009046)) and now I really want to get rid of it entirelly. Any objections? Of course, this should be a subsequent PR. I can tackle it.

2022-09-01 11:47 UTC, german-e-mas commented
Want me to take care of this branch @nkoenig ?

2022-09-03 15:53 UTC, nkoenig commented on angular.json
> +    "gazebosim": {
I copied over changes from `gazebosim-web-frontend`, which I already converted to angular14. These change should make the two project look similar.

2022-09-03 15:53 UTC, nkoenig commented on angular.json
> +      "prefix": "app",
To make it more consistent with the `gazebosim-web-frontend` project.

2022-09-03 15:54 UTC, nkoenig commented on angular.json
> +            "outputPath": "dist",
Is this change necessary?

2022-09-03 16:07 UTC, nkoenig commented on angular.json
> +              "src/sitemap.xml"
I added these files.

2022-09-03 16:14 UTC, nkoenig commented on angular.json
> +              "node_modules/marked/marked.min.js"
We use markdown in model and world description inputs and rendering.

2022-09-03 16:15 UTC, nkoenig commented on angular.json
> +              "node_modules/font-awesome/css/font-awesome.css"
I've removed font-awesome

2022-09-03 16:15 UTC, nkoenig commented on angular.json
> +              "budgets": [
Suggestions?

2022-09-03 16:16 UTC, nkoenig commented on angular.json
> +          "builder": "@angular-devkit/build-angular:karma",
I followed a tutorial for using environment variables. This seems to work.

2022-09-03 16:16 UTC, nkoenig commented on package.json
> +    "font-awesome": "^4.7.0",
I removed font-awesome.

2022-09-03 16:17 UTC, nkoenig commented on src/app/admin/cloudsim/rules/simulation-rules.component.ts
> +    rule.value = Number(this.valueInputForm.value);
I had to make this change in order to make the compiler happy. I'm only changing things that are necessary to run the application.

2022-09-03 16:18 UTC, nkoenig commented on src/app/app.module.ts
> -  entryComponents: [
Yeah, they were deprecated and are no longer needed. I checked this before removing.

2022-09-03 16:21 UTC, nkoenig commented on src/polyfills.ts
> +import 'zone.js';  // Included with Angular CLI.
I think this was changed for me using the angular cli tool during the upgrade process.

2022-09-03 16:43 UTC, nkoenig commented
> The infinite scrolling library should be updated, but I saw this [issue](https://github.com/orizens/ngx-infinite-scroll/issues/352#issue-614626964) (and [potential fix](https://github.com/orizens/ngx-infinite-scroll/issues/352#issuecomment-742009046)) and now I really want to get rid of it entirelly. Any objections? Of course, this should be a subsequent PR. I can tackle it.

Yes, please open a PR to fix this.

2022-09-15 12:58 UTC, german-e-mas commented
Commit https://github.com/gazebo-web/gazebosim-app/pull/8/commits/a0c8c51779ba09070183750f044a9adaed0fa917 removed custom SVGs we were using for the Category and Tags icons.

These were the only use cases, which are now covered (at least in a way) by the regular Material icons. Changed them in https://github.com/gazebo-web/gazebosim-app/pull/8/commits/8e40dd0aeb1c0c820bab152d3fba02199051770a.

Comparison:

| New icons | Old icons |
| --- | --- |
| ![Screenshot from 2022-09-15 09-53-42](https://user-images.githubusercontent.com/14120807/190409499-23f2264b-c5d7-4d93-a3d8-903a83b00610.png) | ![Screenshot from 2022-09-15 09-53-57](https://user-images.githubusercontent.com/14120807/190409502-20e1bf0c-07e3-4615-a2b5-c5f9b6445736.png) |

2022-09-15 13:03 UTC, german-e-mas commented on angular.json
> +            "outputPath": "dist",
It's not as long as we know the build output is inside `dist` rather than `dist/gazebosim`. Older scripts we had shouldn't be used anyways, so this change is safe.

2022-09-15 13:05 UTC, german-e-mas commented on angular.json
> +              "budgets": [
I believe they are just warnings, not errors though (the app will be built regardless). We can fine tune them in the future.

2022-09-15 13:06 UTC, german-e-mas commented on angular.json
> +          "builder": "@angular-devkit/build-angular:karma",
Tests can't be run yet. We can tackle this in a following PR. Migrating tests is not straightforward.

2022-09-15 13:53 UTC, german-e-mas reviewed
Left some comments regarding Swiper. I really think we should move it into it's own component, in order to avoid changing the encapsulation of the components that use it.

2022-09-15 13:53 UTC, german-e-mas commented on src/app/world/world.component.ts
> +  encapsulation: ViewEncapsulation.None
I'm reluctant to set the ViewEncapsulation to None in the Model and World components. This could lead to unwanted behavior if not done thoughtfully. For example, the Model or World styles may be accessible from elsewhere in the app. It's really hard to debug if this happens.

If this is what it takes for the Slider to work, maybe we can create a GalleryComponent that has it, with the bare minimum. I can take a look at that.

2022-09-15 13:53 UTC, german-e-mas commented on src/app/world/world.component.html
> +                    style="--swiper-navigation-color: #000;--swiper-pagination-color: #000"
inline styling should be avoided. Sadly it depends on how easy is to style Swiper.

2022-10-19 16:49 UTC, german-e-mas commented
Just as a heads-up, I'm working on removing the inifnite scroll. That's the last step of the migration. Once that is ready we can merge this. We can work on modules/standalone components on a subsequent PR.

2023-02-08 17:27 UTC, german-e-mas commented
@nkoenig can we rollback the merge of https://github.com/gazebo-web/gazebosim-app/pull/9 into this PR? Without it, the Angular 14 upgrade is ready to be deployed. I haven't tested the gzweb-related changes, so having it here will block the Angular 14 update.

We can treat the changes of https://github.com/gazebo-web/gazebosim-app/pull/9 as an upgrade to use gzweb via npm, which should not be related to the Angular 14 update.

2023-02-08 19:32 UTC, nkoenig commented
> @nkoenig can we rollback the merge of #9 into this PR? Without it, the Angular 14 upgrade is ready to be deployed. I haven't tested the gzweb-related changes, so having it here will block the Angular 14 update.
> 
> We can treat the changes of #9 as an upgrade to use gzweb via npm, which should not be related to the Angular 14 update.

Reverted.

2023-02-08 19:48 UTC, german-e-mas approved these changes
Thanks for the revert! The Angular upgrade should be ready now.

2023-02-09 04:22 UTC, merged